### ISSUE TITLE
Obtener stops en las rutas

### ISSUE THREAD

**Issue by bbaruque** [hca0004/GII17.0T_Trayectorias_Semanticas_1819#15]
Comprobar si se pueden obtener puntos dentro de la ruta en los que se para y cuanto tiempo está parado en cada una (larga-corta)

**Comment by hca0004** [comment]
![imagen](https://user-images.githubusercontent.com/33413596/51628708-04c98c00-1f46-11e9-8d22-b4d1fc9fddf7.png)

### **Problemáticas**
•	Saltos de tiempo: donde están dibujados los círculos se producen saltos en el tiempo por esa razón se producen esas líneas rectas tan largas
•	Discontinuidad: cerca de uno de los puntos anteriores se produce una discontinuidad en el tiempo. A pesar de haber un salto de tiempo de una hora en unos pocos minutos después del sato se produce que el tiempo, en un breve periodo de tiempo no sigue el intervalo habitual que es de 5 segundos.
 
![imagen](https://user-images.githubusercontent.com/33413596/51628677-f11e2580-1f45-11e9-8a3e-ea3d34a5d56f.png)

•	Estar parado: a que consideramos que está en un punto
•	Ruido: si nos fijamos hay dos áreas en la parte superior derecha de la imagen donde hay una gran concentración de puntos. El que esta a la derecha se trata de un centro comercial entre algunos de esos puntos hay distancias de hasta 95 metros en 5 segundos. Probablemente sean fallos del GPS y habría que suavizar esos “pequeños saltos”. Si no eliminamos esto es imposible determinar si está parado.

**Comment by hca0004** [comment]
Se ha conseguido obtener Stops pero son un poco deficientes

**Comment by hca0004** [comment]
Se termino en el Hito6, era mas complicado de lo que parecía.
